# -*- coding: utf-8 -*-
"""cvlab4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16H04WLu0rlIr7xvxiOmiUPozzPMjYtBm
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Function to display images
def show_comparison(original, sobel, prewitt, canny):
    plt.figure(figsize=(12, 10))

    # Original image
    plt.subplot(2, 2, 1)
    plt.imshow(original, cmap='gray')
    plt.title('Original Grayscale Image')
    plt.axis('off')

    # Sobel edge detection
    plt.subplot(2, 2, 2)
    plt.imshow(sobel, cmap='gray')
    plt.title('Sobel Edge Detection')
    plt.axis('off')

    # Prewitt edge detection
    plt.subplot(2, 2, 3)
    plt.imshow(prewitt, cmap='gray')
    plt.title('Prewitt Edge Detection')
    plt.axis('off')

    # Canny edge detection
    plt.subplot(2, 2, 4)
    plt.imshow(canny, cmap='gray')
    plt.title('Canny Edge Detection')
    plt.axis('off')

    plt.tight_layout()
    plt.show()


# 1. Read an image
img = cv2.imread('/content/kohli.jpg', 0)

if img is None:
    print("Error: Image not found. Check the path /content/kohli.jpg")
else:

    # -----------------------------
    # 2. Sobel Edge Detection
    # -----------------------------

    # Gradient in X direction
    sobelx = cv2.Sobel(img, cv2.CV_64F, 1, 0, ksize=3)

    # Gradient in Y direction
    sobely = cv2.Sobel(img, cv2.CV_64F, 0, 1, ksize=3)

    # Combine X and Y gradients
    sobel_combined = cv2.magnitude(sobelx, sobely)

    # Convert to uint8
    sobel_combined = cv2.convertScaleAbs(sobel_combined)


    # -----------------------------
    # 3. Prewitt Edge Detection
    # -----------------------------

    kernelx = np.array([
        [-1, 0, 1],
        [-1, 0, 1],
        [-1, 0, 1]
    ], dtype=np.float32)

    kernely = np.array([
        [-1, -1, -1],
        [ 0,  0,  0],
        [ 1,  1,  1]
    ], dtype=np.float32)

    # Apply Prewitt kernels
    prewittx = cv2.filter2D(img, cv2.CV_64F, kernelx)
    prewitty = cv2.filter2D(img, cv2.CV_64F, kernely)

    # Combine gradients
    prewitt_combined = cv2.magnitude(prewittx, prewitty)

    # Convert to uint8
    prewitt_combined = cv2.convertScaleAbs(prewitt_combined)


    # -----------------------------
    # 4. Canny Edge Detection
    # -----------------------------

    canny_edges = cv2.Canny(img, 100, 200)


    # -----------------------------
    # 5. Display Results
    # -----------------------------

    show_comparison(
        img,
        sobel_combined,
        prewitt_combined,
        canny_edges
    )